spring:
  #Database를 H2로 사용하기 위해 H2연결 정보 입력
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/blogsearch;AUTO_SERVER=true  # H2 접속 정보
    username: sa
    password: 
  jpa: 
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson.serialization.fail-on-empty-beans: false
        
# API 사용을 위한 properties
api:
  key:
    kakao: KakaoAK ff433b9df9b44c4c80f606d936538f6c
    naver:
      id: YkTR6tD79R9cPkh0VdsI
      secret: KKYj8N2Mk7
  url:
    kakao: https://dapi.kakao.com/v2/search/blog
    naver: https://openapi.naver.com/v1/search/blog.json

    